import mongoose from "mongoose";

const Schema = mongoose.Schema;

//This schema is only available for mongoose the mongodb itself does not care since it is schemaless
//id is autogenerated
const MatchSchema = new Schema({
    AdoptiveParentId: {
        //below is the metadata for the property name
        type: String,
        required: true
    },
    ChildId: {
        type: String,
        required: true
    },
    MatchStatus: {
        type: String,
        required: true
    }
    // location: {
    //     room: {
    //         type: String,
    //         required: true
    //     },

    //     building: {
    //         type: String,
    //         required: true
    //     }
    // },
    // schedule: {
    //     startTime: {
    //         type: String,
    //         required: true
    //     },
    //     endTime: {
    //         type: String
    //     }
    // }
},
{
    //Prevent the default behaviour of the version key which creates a property version key automatically, this is an optional parameter
    versionKey: false
});

//Creating the model using the schema
const MatchModel = mongoose.model('match', MatchSchema);

export default MatchModel;